files:
  - source: /src/**/en_us.json
    translation: /done/%original_path%/%locale_with_underscore%.json
  - source: /src/Alex's Caves/books/**/*.txt
    translation: /done/src/Alex's Caves/books/%locale_with_underscore%/%original_path%/%original_file_name%
